// Code generated by MockGen. DO NOT EDIT.
// Source: bookings_repository.go
//
// Generated by this command:
//
//	mockgen -source=bookings_repository.go -destination=bookings_repository_mock.go -package=domain github.com/arngrimur/bilcool_monolith/bookings
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/arngrimur/bilcool_monolith/bookings/pkg/domain"
	postgres "github.com/arngrimur/bilcool_monolith/message_broker/pkg/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingsRepository is a mock of BookingsRepository interface.
type MockBookingsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingsRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingsRepositoryMockRecorder is the mock recorder for MockBookingsRepository.
type MockBookingsRepositoryMockRecorder struct {
	mock *MockBookingsRepository
}

// NewMockBookingsRepository creates a new mock instance.
func NewMockBookingsRepository(ctrl *gomock.Controller) *MockBookingsRepository {
	mock := &MockBookingsRepository{ctrl: ctrl}
	mock.recorder = &MockBookingsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingsRepository) EXPECT() *MockBookingsRepositoryMockRecorder {
	return m.recorder
}

// AddTrackPoints mocks base method.
func (m *MockBookingsRepository) AddTrackPoints(ctx context.Context, request AddTrackPointsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTrackPoints", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTrackPoints indicates an expected call of AddTrackPoints.
func (mr *MockBookingsRepositoryMockRecorder) AddTrackPoints(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTrackPoints", reflect.TypeOf((*MockBookingsRepository)(nil).AddTrackPoints), ctx, request)
}

// AddUser mocks base method.
func (m *MockBookingsRepository) AddUser(ctx context.Context, message postgres.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockBookingsRepositoryMockRecorder) AddUser(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockBookingsRepository)(nil).AddUser), ctx, message)
}

// DeleteBooking mocks base method.
func (m *MockBookingsRepository) DeleteBooking(ctx context.Context, request BookingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooking", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooking indicates an expected call of DeleteBooking.
func (mr *MockBookingsRepositoryMockRecorder) DeleteBooking(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooking", reflect.TypeOf((*MockBookingsRepository)(nil).DeleteBooking), ctx, request)
}

// DeleteUser mocks base method.
func (m *MockBookingsRepository) DeleteUser(ctx context.Context, message postgres.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockBookingsRepositoryMockRecorder) DeleteUser(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockBookingsRepository)(nil).DeleteUser), ctx, message)
}

// EndBooking mocks base method.
func (m *MockBookingsRepository) EndBooking(ctx context.Context, request EndBookingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndBooking", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndBooking indicates an expected call of EndBooking.
func (mr *MockBookingsRepositoryMockRecorder) EndBooking(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndBooking", reflect.TypeOf((*MockBookingsRepository)(nil).EndBooking), ctx, request)
}

// Find mocks base method.
func (m *MockBookingsRepository) Find(ctx context.Context, request BookingRequest) (domain.BookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, request)
	ret0, _ := ret[0].(domain.BookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockBookingsRepositoryMockRecorder) Find(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockBookingsRepository)(nil).Find), ctx, request)
}

// FindAll mocks base method.
func (m *MockBookingsRepository) FindAll(ctx context.Context) ([]domain.BookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]domain.BookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBookingsRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBookingsRepository)(nil).FindAll), ctx)
}

// GetTrackPoints mocks base method.
func (m *MockBookingsRepository) GetTrackPoints(ctx context.Context, request BookingRequest) ([]domain.TrackPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrackPoints", ctx, request)
	ret0, _ := ret[0].([]domain.TrackPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrackPoints indicates an expected call of GetTrackPoints.
func (mr *MockBookingsRepositoryMockRecorder) GetTrackPoints(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrackPoints", reflect.TypeOf((*MockBookingsRepository)(nil).GetTrackPoints), ctx, request)
}

// PauseBooking mocks base method.
func (m *MockBookingsRepository) PauseBooking(ctx context.Context, request PauseBookingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseBooking", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseBooking indicates an expected call of PauseBooking.
func (mr *MockBookingsRepositoryMockRecorder) PauseBooking(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseBooking", reflect.TypeOf((*MockBookingsRepository)(nil).PauseBooking), ctx, request)
}

// ResumeBooking mocks base method.
func (m *MockBookingsRepository) ResumeBooking(ctx context.Context, request BookingRequest) (PauseBookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeBooking", ctx, request)
	ret0, _ := ret[0].(PauseBookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeBooking indicates an expected call of ResumeBooking.
func (mr *MockBookingsRepositoryMockRecorder) ResumeBooking(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeBooking", reflect.TypeOf((*MockBookingsRepository)(nil).ResumeBooking), ctx, request)
}

// UpdateBooking mocks base method.
func (m *MockBookingsRepository) UpdateBooking(ctx context.Context, request UpdateBookingRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBooking", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBooking indicates an expected call of UpdateBooking.
func (mr *MockBookingsRepositoryMockRecorder) UpdateBooking(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBooking", reflect.TypeOf((*MockBookingsRepository)(nil).UpdateBooking), ctx, request)
}
