services:
  booking-database:
    image: postgres:18
    container_name: bookings-db
    ports: ["54321:5432"]
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bookings
      POSTGRES_INITDB_ARGS: "-c wal_level=logical -c max_wal_senders=5 -c max_replication_slots=5"
    networks:
      - booking-network
      - bilcool

  db-migration-booking:
    image: amacneil/dbmate
    entrypoint: ["/bin/sh", "-c",  "dbmate --wait --migrations-dir /migrations migrate"]
    volumes:
      - "./migrations:/migrations"
    depends_on:
      - booking-database
    environment:
      DATABASE_URL: postgres://postgres:postgres@bookings-db:5432/bookings?sslmode=disable
    networks:
      - booking-network

networks:
  booking-network:
  bilcool:


