// Code generated by MockGen. DO NOT EDIT.
// Source: event_handler.go
//
// Generated by this command:
//
//	mockgen -source=event_handler.go -destination=sqs_client_mock.go -package=inbox
//

// Package inbox is a generated GoMock package.
package inbox

import (
	context "context"
	reflect "reflect"

	postgres "github.com/arngrimur/bilcool_monolith/message_broker/pkg/postgres"
	gomock "go.uber.org/mock/gomock"
)

// MocksqsClient is a mock of sqsClient interface.
type MocksqsClient struct {
	ctrl     *gomock.Controller
	recorder *MocksqsClientMockRecorder
	isgomock struct{}
}

// MocksqsClientMockRecorder is the mock recorder for MocksqsClient.
type MocksqsClientMockRecorder struct {
	mock *MocksqsClient
}

// NewMocksqsClient creates a new mock instance.
func NewMocksqsClient(ctrl *gomock.Controller) *MocksqsClient {
	mock := &MocksqsClient{ctrl: ctrl}
	mock.recorder = &MocksqsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksqsClient) EXPECT() *MocksqsClientMockRecorder {
	return m.recorder
}

// DeleteMessages mocks base method.
func (m *MocksqsClient) DeleteMessages(ctx context.Context, messages []postgres.Message) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessages", ctx, messages)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessages indicates an expected call of DeleteMessages.
func (mr *MocksqsClientMockRecorder) DeleteMessages(ctx, messages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessages", reflect.TypeOf((*MocksqsClient)(nil).DeleteMessages), ctx, messages)
}

// RetrieveMessages mocks base method.
func (m *MocksqsClient) RetrieveMessages(ctx context.Context) ([]postgres.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveMessages", ctx)
	ret0, _ := ret[0].([]postgres.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveMessages indicates an expected call of RetrieveMessages.
func (mr *MocksqsClientMockRecorder) RetrieveMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveMessages", reflect.TypeOf((*MocksqsClient)(nil).RetrieveMessages), ctx)
}

// VisibilityTimeout mocks base method.
func (m *MocksqsClient) VisibilityTimeout() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VisibilityTimeout")
	ret0, _ := ret[0].(int)
	return ret0
}

// VisibilityTimeout indicates an expected call of VisibilityTimeout.
func (mr *MocksqsClientMockRecorder) VisibilityTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisibilityTimeout", reflect.TypeOf((*MocksqsClient)(nil).VisibilityTimeout))
}
