server {
    listen 80;

    location /api/v1/users {
        add_header Cache-Control "no-store";
        proxy_pass http://authentication:8080;
        proxy_set_header Host $host;
    }

    location /api/v1/bookings {
        add_header Cache-Control "no-store";
        proxy_pass http://bookings:8080;
        proxy_set_header Host $host;
    }

    location /api/v1/events {
        add_header Cache-Control "no-store";
        proxy_pass http://event-ledger:8080;
        proxy_set_header Host $host;
    }

    location /api/v1/journal {
        add_header Cache-Control "no-store";
        proxy_pass http://journal:8080;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
