server {
    listen 80;

    location /api/auth/ {
        proxy_pass http://authentication:8080/;
    }

    location /api/book/ {
        proxy_pass http://bookings:8080/;
    }

    location /api/events/ {
        proxy_pass http://event-ledger:8080/;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
