// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go
//
// Generated by this command:
//
//	mockgen -source=publisher.go -destination=publisher_mock.go -package=sns github.com/arngrimur/bilcool_monolith/message_broker
//

// Package sns is a generated GoMock package.
package sns

import (
	context "context"
	reflect "reflect"

	postgres "github.com/arngrimur/bilcool_monolith/message_broker/pkg/postgres"
	sns "github.com/aws/aws-sdk-go-v2/service/sns"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// SendBatchMessages mocks base method.
func (m *MockPublisher) SendBatchMessages(ctx context.Context, events []postgres.Event, topic string) (*sns.PublishBatchOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatchMessages", ctx, events, topic)
	ret0, _ := ret[0].(*sns.PublishBatchOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendBatchMessages indicates an expected call of SendBatchMessages.
func (mr *MockPublisherMockRecorder) SendBatchMessages(ctx, events, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatchMessages", reflect.TypeOf((*MockPublisher)(nil).SendBatchMessages), ctx, events, topic)
}

// SendMessage mocks base method.
func (m *MockPublisher) SendMessage(ctx context.Context, event postgres.Event, topic string) (*sns.PublishOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, event, topic)
	ret0, _ := ret[0].(*sns.PublishOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockPublisherMockRecorder) SendMessage(ctx, event, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockPublisher)(nil).SendMessage), ctx, event, topic)
}

// MockSnsClientAPI is a mock of SnsClientAPI interface.
type MockSnsClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSnsClientAPIMockRecorder
	isgomock struct{}
}

// MockSnsClientAPIMockRecorder is the mock recorder for MockSnsClientAPI.
type MockSnsClientAPIMockRecorder struct {
	mock *MockSnsClientAPI
}

// NewMockSnsClientAPI creates a new mock instance.
func NewMockSnsClientAPI(ctrl *gomock.Controller) *MockSnsClientAPI {
	mock := &MockSnsClientAPI{ctrl: ctrl}
	mock.recorder = &MockSnsClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnsClientAPI) EXPECT() *MockSnsClientAPIMockRecorder {
	return m.recorder
}

// CreateTopic mocks base method.
func (m *MockSnsClientAPI) CreateTopic(ctx context.Context, params *sns.CreateTopicInput, optFns ...func(*sns.Options)) (*sns.CreateTopicOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTopic", varargs...)
	ret0, _ := ret[0].(*sns.CreateTopicOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockSnsClientAPIMockRecorder) CreateTopic(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockSnsClientAPI)(nil).CreateTopic), varargs...)
}

// ListTopics mocks base method.
func (m *MockSnsClientAPI) ListTopics(ctx context.Context, params *sns.ListTopicsInput, optFns ...func(*sns.Options)) (*sns.ListTopicsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTopics", varargs...)
	ret0, _ := ret[0].(*sns.ListTopicsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockSnsClientAPIMockRecorder) ListTopics(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockSnsClientAPI)(nil).ListTopics), varargs...)
}

// Publish mocks base method.
func (m *MockSnsClientAPI) Publish(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(*sns.PublishOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockSnsClientAPIMockRecorder) Publish(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSnsClientAPI)(nil).Publish), varargs...)
}

// PublishBatch mocks base method.
func (m *MockSnsClientAPI) PublishBatch(ctx context.Context, params *sns.PublishBatchInput, optFns ...func(*sns.Options)) (*sns.PublishBatchOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PublishBatch", varargs...)
	ret0, _ := ret[0].(*sns.PublishBatchOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishBatch indicates an expected call of PublishBatch.
func (mr *MockSnsClientAPIMockRecorder) PublishBatch(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBatch", reflect.TypeOf((*MockSnsClientAPI)(nil).PublishBatch), varargs...)
}
