apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings
  labels:
    app: bookings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookings
  template:
    metadata:
      name: bookings
      labels:
        app: bookings
    spec:
      containers:
        - name: bookings
          image: arngrimur/bilcool-bookings:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: bilcool-shared
            - secretRef:
                name: bookings
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bookings
spec:
  selector:
    app: bookings
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
