apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal
  labels:
    app: journal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: journal
  template:
    metadata:
      name: journal
      labels:
        app: journal
    spec:
      containers:
        - name: journal
          image: arngrimur/bilcool-journal:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: bilcool-shared
            - secretRef:
                name: journal
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: journal
spec:
  selector:
    app: journal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
