apiVersion: v1
kind: Secret
metadata:
  name: authentication
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.authentication.jwtSecret | quote }}
  BREVO_API_KEY: {{ .Values.secrets.authentication.brevoApiKey | quote }}
  DATABASE_URL: {{ .Values.secrets.authentication.databaseUrl | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bookings
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.bookings.databaseUrl | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: journal
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.journal.databaseUrl | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: event-ledger
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
