// Code generated by MockGen. DO NOT EDIT.
// Source: actions.go
//
// Generated by this command:
//
//	mockgen -source=actions.go -destination=actions_mock.go -package=outbox github.com/arngrimur/bilcool_monolith/outbox Actions
//

// Package outbox is a generated GoMock package.
package outbox

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAction is a mock of Action interface.
type MockAction struct {
	ctrl     *gomock.Controller
	recorder *MockActionMockRecorder
	isgomock struct{}
}

// MockActionMockRecorder is the mock recorder for MockAction.
type MockActionMockRecorder struct {
	mock *MockAction
}

// NewMockAction creates a new mock instance.
func NewMockAction(ctrl *gomock.Controller) *MockAction {
	mock := &MockAction{ctrl: ctrl}
	mock.recorder = &MockActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAction) EXPECT() *MockActionMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAction) Execute(table Table) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Execute", table)
}

// Execute indicates an expected call of Execute.
func (mr *MockActionMockRecorder) Execute(table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAction)(nil).Execute), table)
}
