basePath: /api/v1
definitions:
  domain.BookingResponse:
    properties:
      booking_reference:
        example: 123e4567-e89b-12d3-a456-426655440000
        type: string
      end_date:
        example: "2021-01-01 12:00:00"
        type: string
      start_date:
        example: "2021-01-01 10:00:00"
        type: string
      user_ref:
        example: 123e4567-e89b-12d3-a456-426655440000
        type: string
    required:
    - booking_reference
    - end_date
    - start_date
    - user_ref
    type: object
  web.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: The REST API for BilCool to book and view bookings and other stuff.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BilCool REST API
  version: "1.0"
paths:
  /bookings:
    get:
      consumes:
      - application/json
      description: get all booking
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.BookingResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.HTTPError'
      summary: List all bookings
      tags:
      - bookings
    post:
      consumes:
      - application/json
      description: Update or add a new booking
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.BookingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.HTTPError'
      tags:
      - bookings
  /bookings/{id}:
    get:
      consumes:
      - application/json
      description: get booking by booking reference
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.BookingResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.HTTPError'
      summary: Show a booking
      tags:
      - bookings
securityDefinitions:
  None:
    type: basic
swagger: "2.0"
