name: Build

on:
  push:
    branches: [*]
  pull_request:
    branches: [main]

jobs:
  build-testing:
    name: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: testing/go.mod
          cache-dependency-path: testing/go.sum
      - name: Install task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest
      - run: go mod tidy
        working-directory: testing
      - run: go mod vendor
        working-directory: testing
      - run: task testing:build

  build-message-broker:
    name: message_broker
    runs-on: ubuntu-latest
    needs: build-testing
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: message_broker/go.mod
          cache-dependency-path: message_broker/go.sum
      - name: Install task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - run: go mod tidy
        working-directory: message_broker
      - run: go mod vendor
        working-directory: message_broker
      - run: task message_broker:build
      - run: task message_broker:test
      - run: task message_broker:integration-test

  build-bookings:
    name: bookings
    runs-on: ubuntu-latest
    needs: [build-testing, build-message-broker]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: bookings/go.mod
          cache-dependency-path: bookings/go.sum
      - name: Install task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - run: go mod tidy
        working-directory: bookings
      - run: go mod vendor
        working-directory: bookings
      - run: task bookings:build
      - run: task bookings:integration-test
